faketime.c: fix shared_objs[] array size
shared_objs[] will contain the concatenation of sem_name and shm_name,
which are both 4096 bytes long, and shared_objs[] itself is only 4096
bytes long. This causes a build failure with gcc 8.x:

faketime.c: In function 'main':
faketime.c:289:45: error: '%s' directive output may be truncated writing up to 4095 bytes into a region of size between 0 and 4095 [-Werror=format-truncation=]
     snprintf(shared_objs, PATH_BUFSIZE, "%s %s", sem_name, shm_name);
                                             ^~             ~~~~~~~~
faketime.c:289:5: note: 'snprintf' output between 2 and 8192 bytes into a destination of size 4096
     snprintf(shared_objs, PATH_BUFSIZE, "%s %s", sem_name, shm_name);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This commit fixes that by enlarging the shared_objs[] array to twice
the of PATH_BUFSIZE, plus one byte for the space.

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>